# ===============================
#  Prettier Configuration
# ===============================

# 💡 Общие настройки
printWidth: 100 # максимально допустимая длина строки
tabWidth: 2 # размер отступа — 2 пробела
useTabs: false # использовать пробелы вместо табов
semi: false # без точек с запятой (актуально для JS, на YAML не влияет)
singleQuote: false # двойные кавычки для строк
trailingComma: none # не ставить запятые в конце списков / объектов
bracketSpacing: true # пробелы внутри фигурных скобок
arrowParens: always # всегда добавлять скобки вокруг аргументов стрелочных функций
proseWrap: always # переносить длинные строки в Markdown
endOfLine: lf # перенос строк в UNIX-стиле
quoteProps: as-needed # кавычки только когда нужны

# 🧩 YAML и TOML
yamlBracketSpacing: true
yamlQuoteStyle: double # использовать двойные кавычки
yamlSortKeys: false # не сортировать ключи
embeddedLanguageFormatting: auto

# 📄 Markdown
overrides:
  - files: "*.md"
    options:
      printWidth: 80 # Markdown удобнее читать с меньшей шириной
      proseWrap: always

  # 🧰 JSON
  - files: "*.json"
    options:
      trailingComma: none
      quoteProps: preserve
      singleQuote: false

  # 🧾 TOML
  - files: "*.toml"
    options:
      parser: toml
