# ===============================
# Pre-commit configuration
# ===============================
# Install:
#   pip install pre-commit
#   pre-commit install && pre-commit install -t pre-push
# Skip checks:
#   git commit --no-verify

fail_fast: false

# default_install_hook_types: ["pre-commit", "commit-msg"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix, --exit-zero]
      - id: ruff-format

  - repo: https://github.com/crate-ci/committed
    rev: v1.1.7
    hooks:
      - id: committed

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
