services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - client_dist:/app/dist
    restart: no

  proxy:
    image: nginx:1.27-alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - client_dist:/usr/share/nginx/html
      - ./docker/confs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/confs/nginx/sites:/etc/nginx/conf.d:ro
    depends_on:
      client:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  client_dist:
