[files]
extend-exclude = [
  "data/",
  "client/dist/",
  ".git/",
  ".venv/",
  "venv/",
  "node_modules/",
  "data/dispatch-sample-data.dump"
]

# Добавляем собственные словарные исключения (разрешённые слова)
[default.extend-words]
API = "API"
uuid = "uuid"
pytest = "pytest"
asyncio = "asyncio"
typos = "typos"
ruff = "ruff"
pytestcov = "pytestcov"
Dockerfile = "Dockerfile"
yaml = "yaml"
uvicorn = "uvicorn"
mypy = "mypy"
